build:
    environment:
        php: '7.0.8'
    tests:
        override:
            - phpcs-run .
checks:
    php: true
coding_style:
    php:
        indentation:
            general:
                size: 2
        spaces:
            before_parentheses:
                closure_definition: true
        braces:
            classes_functions:
                class: end-of-line
                function: end-of-line
                closure: end-of-line
            if:
                opening: end-of-line
                else_on_new_line: true
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
                while_on_new_line: true
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
                catch_on_new_line: true
                finally_on_new_line: true
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: upper
tools:
    php_code_sniffer:
        config:
            standard: "Drupal"
