language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - DRUPAL_CORE=8.1.x
    CODE_REVIEW=0
    SIMPLETEST_DB=mysql://root:@127.0.0.1/og
    SIMPLETEST_BASE_URL=http://localhost:8888
  - DRUPAL_CORE=8.2.x
    CODE_REVIEW=0
    SIMPLETEST_DB=mysql://root:@127.0.0.1/og
    SIMPLETEST_BASE_URL=http://localhost:8888
  - REVIEW_STANDARD="Drupal"
    CODE_REVIEW=1
  - REVIEW_STANDARD="DrupalPractice"
    CODE_REVIEW=1

mysql:
  database: og
  username: root
  encoding: utf8

before_install:
  # Remove Xdebug as we don't need it and it causes "PHP Fatal error: Maximum
  # function nesting level of '256' reached."
  # We also don't care if that file exists or not on PHP 7.
  - phpenv config-rm xdebug.ini || true

  # Install Composer dependencies.
  - composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

install:
  # Remember the current directory for later use in the Drupal installation.
  - TESTDIR=$(pwd)

  - travis_retry $TRAVIS_BUILD_DIR/travis/prepare_tests.sh
  - $TRAVIS_BUILD_DIR/travis/prepare_coder.sh

  - phpenv rehash

script:
  - $TRAVIS_BUILD_DIR/travis/run_tests.sh
  - $TRAVIS_BUILD_DIR/travis/run_coder.sh
