field.storage_settings.og_membership_reference:
  type: mapping
  label: 'Organic Groupds reference field storage settings'
  mapping:
    target_type:
      type: string
      label: 'Type of entity to reference'

field.field_settings.og_membership_reference:
  type: mapping
  label: 'Organic Groupds reference field settings'
  mapping:
    handler:
      type: string
      label: 'Reference method'
    handler_settings:
      type: entity_reference_selection.[%parent.handler]
      label: 'Organic Groupds reference selection plugin settings'

og.settings:
  type: config_object
  label: 'Organic Groups settings'
  mapping:
    groups:
      type: sequence
      sequence:
        type: og.settings.group.[%key]

og.settings.group.*:
  type: sequence
  label: 'OG groups'
  sequence:
    type: string
    label: 'Group'

og.og_membership_type.*:
  type: config_entity
  label: 'OG membership type'
  mapping:
    type:
      type: string
      label: 'ID'
    name:
      type: string
      label: 'Name'
    description:
      type: string
      label: 'Description'
    status:
      type: boolean
      label: 'Status'
