<?php
/**
 * @file
 * Contains
 */
use Drupal\Component\Utility\Unicode;
use Drupal\Core\Config\Entity\ConfigEntityBundleBase;
use Drupal\Core\Entity\BundleEntityFormBase;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\field\Entity\FieldConfig;
use Drupal\field_ui\FieldUI;
use Drupal\og\Og;

/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function og_ui_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_state->getFormObject() instanceof BundleEntityFormBase) {
    // This is an entity type, which of course, is an entity...
    /** @var \Drupal\Core\Entity\EntityInterface $entity */
    $entity = $form_state->getFormObject()->getEntity();
    // Example: article.
    $bundle = $entity->id();
    $definition = \Drupal::entityTypeManager()->getDefinition($entity->getEntityTypeId());
    // Example: node.
    $entity_type_id = $definition->getBundleOf();
    if (!$entity_type_id) {
      return;
    }
    $form['og'] = array(
      '#type' => 'fieldset',
      '#title' => t('Organic groups'),
      '#collapsible' => TRUE,
      '#group' => 'additional_settings',
      '#description' => t('Each "@bundle" may serve as a group, may belong to a group, or may not participate in OG at all.', [
        // Example: Article.
        '@bundle' => Unicode::lcfirst($entity->label()),
      ]),
    );
    $is_group = Og::isGroup($entity_type_id, $bundle);
    $description = t('Set the content type to be a group, that content will be associated with, and will have group members.');
    if ($is_group) {
      $url = Link::createFromRoute(t('Manage fields'), FieldUI::getOverviewRouteInfo($entity_type_id, $bundle));
      $description .= '<br/>' . t('To unset the group definition you should delete the "Group type" field via @url.', ['@url' => $url]);
    }
    $form['og']['og_group_type'] = array(
      '#type' => 'checkbox',
      '#title' => t('Group'),
      '#default_value' => $is_group,
      '#description' => $description,
      '#disabled' => $is_group,
    );
    // Group content settings.
    $is_group_content = Og::isGroupContent($entity_type_id, $bundle);
    $description = t('Set the content type to be a group content, that can be associated with groups.');
    if ($is_group_content) {
      $description .= '<br/>' . t('To unset the group content definition or change the settings you should delete the "Groups audience" field via !url.', $url);
    }
    $group_content_options = Og::groupManager()->getGroupsForEntityType($entity_type_id);
    if (!$group_content_options) {
      $description .= '<br/>' . t('There are no group bundles defined.');
    }

    $form['og']['og_group_content_bundle'] = array(
      '#type' => 'checkbox',
      '#title' => t('Group content'),
      '#default_value' =>  $is_group_content,
      '#description' => $description,
      '#disabled' => !$group_content_options || $is_group_content,
    );

    if ($group_content_options) {
      // Don't show the settings, as there might be multiple OG audience fields
      // in the same bundle.
      $form['og']['target_type'] = array(
        '#type' => 'select',
        '#title' => t('Target type'),
        '#options' => $group_content_options,
        '#default_value' => key($group_content_options),
        '#description' => t('The entity type that can be referenced thru this field.'),
        '#ajax' => array(
          'callback' => 'og_ui_entity_type_form_settings',
          'wrapper' => 'og-settings-wrapper',
        ),
        '#states' => array(
          'visible' => array(
            ':input[name="og_group_content_bundle"]' => array('checked' => TRUE),
          ),
        ),
      );

      $target_type = $form_state->hasValue('target_type') ? $form_state->getValue('target_type') : key($group_content_options);
      $bundles = \Drupal::service('entity_type.bundle.info')->getBundleInfo($entity_type_id);
      foreach ($bundles as $bundle_name => $bundle_info) {
        if (Og::isGroup($target_type, $bundle_name)) {
          $bundle_options[$bundle_name] = $bundle_info['label'];
        }
      }
      $default_value = [];
      $field = FieldConfig::loadByName($entity_type_id, $bundle, OG_AUDIENCE_FIELD);
      if ($field) {
        $handler_settings = $field->getSetting('handler_settings');
        if (isset($handler_settings['target_bundles'])) {
          $default_value = $handler_settings['target_bundles'];
        }
      }

      // Get the bundles that are acting as group.
      $form['og']['target_bundles'] = array(
        '#prefix' => '<div id="og-settings-wrapper">',
        '#suffix' => '</div>',
        '#type' => 'select',
        '#title' => t('Target bundles'),
        '#options' => $bundles,
        '#default_value' => $default_value,
        '#size' => 6,
        '#multiple' => TRUE,
        '#description' => t('The bundles of the entity type that can be referenced. Optional, leave empty for all bundles.'),
        '#states' => array(
          'visible' => array(
            ':input[name="og_group_content_bundle"]' => array('checked' => TRUE),
          ),
        ),
      );
    }
  }
}

/**
 * AJAX callback to attach the message type fields to the form.
 *
 * Since the controlling logic for populating the form is in the form builder
 * function, all we do here is select the element and return it to be updated.
 */
function og_ui_entity_type_form_settings(array $form, array &$form_state) {
  return $form['og']['target_bundles'];
}

/**
 * Implements hook_entity_insert().
 */
function og_ui_entity_insert(EntityInterface $entity) {
  og_ui_entity_type_save($entity);
}

/**
 * Implements hook_entity_insert().
 */
function og_ui_entity_update(EntityInterface $entity) {
  og_ui_entity_type_save($entity);
}

function og_ui_entity_type_save(EntityInterface $entity) {
  if (!$entity instanceof ConfigEntityBundleBase || !isset($entity->og_group_type) || !isset($entity->og_group_content_bundle)) {
    return;
  }
  $bundle = $entity->id();
  $definition = \Drupal::entityTypeManager()->getDefinition($entity->getEntityTypeId());
  $entity_type_id = $definition->getBundleOf();
  $is_group = Og::isGroup($entity_type_id, $bundle);
  if ($entity->og_group_type != $is_group) {
    if ($is_group) {
      Og::groupManager()->removeGroup($entity_type_id, $bundle);
    }
    else {
      Og::groupManager()->addGroup($entity_type_id, $bundle);
    }
  }
  $is_group_content = Og::isGroupContent($entity_type_id, $bundle);
  if ($entity->og_group_content_bundle != $is_group_content) {
    if ($is_group_content) {
      Og::createField($entity_type_id, $bundle);
    }
    elseif ($field = FieldConfig::loadByName($entity_type_id, $bundle, OG_AUDIENCE_FIELD)) {
      $field->delete();
      return;
    }
  }
  if ($field = FieldConfig::loadByName($entity_type_id, $bundle, OG_AUDIENCE_FIELD)) {
    $handler_settings = $field->getSetting('handler_settings');
    if (!isset($handler_settings['target_bundles']) || $entity->target_bundles != $handler_settings['target_bundles']) {
      $handler_settings['target_bundles'] = $entity->target_bundles;
      $field->setSetting('handler_settings', $handler_settings);
      $field->save();
    }
  }
}
